name: CI Build

on: [push, pull_request, workflow_dispatch]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
        lfs: 'true'
    - run: git fetch --tags

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Debug --no-restore

    - name: Test
      run: dotnet test -c Debug

    - name: Pack
      run: dotnet pack -c Debug -o ${{ github.workspace }}/build

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: dev-build
        path: ${{ github.workspace }}/build/*.nupkg
